### ISSUE TITLE
Can't use explicit abbreviation mode with "auto_mark": false 

### ISSUE THREAD

**Issue by MOONLIGHTV** [emmetio/sublime-text-plugin#117]
**With abbreviation capturing disabled**, you have several options to expand abbreviations manually:

- Another option is to run Emmet: Enter Abbreviation Mode command: the ⋮> mark indicates that you are in explicit abbreviation mode and everything you type will be treated and validated as Emmet abbreviation. You can then hit Tab or Enter key to expand it, Esc to dispose.

**settings:**
` "auto_mark": false,` 

** key bindings:**
` {
        "keys": ["ctrl+."],
        "command": "emmet_enter_abbreviation"
    },`

**When I press "ctrl+." or enter explicit abbreviation mode by "ctrl+shift+p" , nothing happended, no ⋮> mark, no explicit abbreviation mode.
What's wrong with it? thers is gif:**
![2](https://user-images.githubusercontent.com/14039419/92987944-c9544a80-f4f9-11ea-9411-1f2e062c1564.gif)

**Comment by sergeche** [comment]
It looks like Emmet doesn’t work as expected. Can you restart ST, open ST console and show me console contents?

**Comment by MOONLIGHTV** [comment]
![1](https://user-images.githubusercontent.com/14039419/93083429-2d773a00-f6c5-11ea-921b-4dd7a8ebff08.gif)
![2](https://user-images.githubusercontent.com/14039419/93083434-2f40fd80-f6c5-11ea-9b16-bb86f3051231.png)

**Comment by sergeche** [comment]
Thanks, looks like there’s an error, will check it out

**Comment by sergeche** [comment]
Fixed in v2.1.18, will be available in few minutes

**Comment by MOONLIGHTV** [comment]
Thank you sir, I'll try later.

**Comment by MOONLIGHTV** [comment]
> Fixed in v2.1.18, will be available in few minutes

I'm tried again, **has ⋮> mark, has  abbreviation capturing underline, but still not abbreviation  preview.**
![1](https://user-images.githubusercontent.com/14039419/93285107-a9c56680-f806-11ea-8abd-9b716a1d4547.gif)

**Comment by michaelalandawson** [comment]
ST3 3211, Emmet 2.1.18, Windows 10

It worked for me.  I ran the command from the Command Palette rather than a key binding, if that makes any difference.

![117](https://user-images.githubusercontent.com/39276677/93394977-b6fc4880-f83a-11ea-8eba-0b1000337fa6.png)

**Comment by MOONLIGHTV** [comment]
> ST3 3211, Emmet 2.1.18, Windows 10
> 
> It worked for me. I ran the command from the Command Palette rather than a key binding, if that makes any difference.
> 
> ![117](https://user-images.githubusercontent.com/39276677/93394977-b6fc4880-f83a-11ea-8eba-0b1000337fa6.png)

Dude, did you add  "auto_mark": false or other settings ?

**Comment by michaelalandawson** [comment]
@MOONLIGHTV   Sorry, I did not have "auto_mark" set to false.  Thank you for asking.

I added this to my Emmet settings file:
"auto_mark": false

Now, I can confirm the issue still remains on ST3 3211, Emmet 2.1.18, Windows 10.

The abbreviation is "captured" as denoted by the underscore, however, it does not show the preview.
