### ISSUE TITLE
Vue Single-File Components: preview flickering

### ISSUE THREAD

**Issue by rubjo** [emmetio/sublime-text-plugin#156]
Hi,

Thanks for making this plugin!

Sublime Text 4: In Vue SFCs, the preview usually doesn't stay visible when typing. (Usually as in 99% of the time)

Behaviour with regular HTML syntax: as expected
https://user-images.githubusercontent.com/42270947/110908205-c30b2380-830e-11eb-8629-1b404d64057a.mov

Behaviour in a Vue SFC: preview is visible for a split second after a keystroke. On line/abbreviation focus by mouse click, the preview will always show.
https://user-images.githubusercontent.com/42270947/110908592-56445900-830f-11eb-86ec-c787fea923ae.mov

Any ideas? Emmet abbreviations always work when expanding them.

**Comment by sergeche** [comment]
Flickering is caused by ST itself, it should be fixed in recent ST4 version

**Comment by rubjo** [comment]
I'm guessing you are referring to the closed https://github.com/sublimehq/sublime_text/issues/3107.

For me, this still doesn't work on latest ST (4106).

Since it works in a vanilla HTML file, is it possible that https://github.com/vuejs/vue-syntax-highlight breaks the Emmet preview?
